[project]
name = "ctmds1"
version = "0.1.0"
description = ""
authors = [
    {name = "Jimmy Calahorrano",email = "jcalahor@yahoo.com"}
]
readme = "README.md"
requires-python = ">=3.12"


[tool.poetry.dependencies]
python = "^3.12"  # Adjust based on your Python version
click = "8.1.8"
exceptiongroup = "1.2.2"
iniconfig = "2.0.0"
markdown-it-py = "3.0.0"
mdurl = "0.1.2"
numpy = "2.2.2"
packaging = "24.2"
pluggy = "1.5.0"
Pygments = "2.19.1"
pytest = "8.3.4"
rich = "13.9.4"
shellingham = "1.5.4"
tomli = "2.2.1"
typer = "0.15.1"
typing-extensions = "4.12.2"
pytz = "^2025.1"
fastapi = "^0.115.8"
uvicorn = "^0.34.0"
duckdb = "^1.2.0"
httpx = "^0.28.1"
pyyaml = "^6.0.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.6"
typer = "^0.15.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
