name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger only when pushing to the 'main' branch

jobs:
  # Job to test and lint code
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Choose the version that you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run format and lint
        run: |
          make format
          make lint

      - name: Run tests
        run: make test

  # Job to build Docker image
  build_docker_image:
    runs-on: ubuntu-latest
    needs: test_and_lint  # This ensures the Docker image is only built after tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ctmds1:latest .
